INSERT INTO T_USER (USER_ID, USERNAME, PASSWORD, FIRSTNAME, ENABLED) VALUES ('1', 'test', 'test', 'test', true);
INSERT INTO T_USER (USER_ID, USERNAME, PASSWORD, FIRSTNAME, ENABLED) VALUES ('2', 'asdf', 'asdf', 'asdf', true);

INSERT INTO ROLE (ROLE_ID, NAME) VALUES ('1', 'ADMIN');
INSERT INTO ROLE (ROLE_ID, NAME) VALUES ('2', 'USER');

INSERT INTO PRIVILEGE (PRIVILEGE_ID, NAME) VALUES ('0', 'ADMIN');
INSERT INTO PRIVILEGE (PRIVILEGE_ID, NAME) VALUES ('1', 'PERM_VIEW_USER');
INSERT INTO PRIVILEGE (PRIVILEGE_ID, NAME) VALUES ('2', 'PERM_DELETE_USER');
INSERT INTO PRIVILEGE (PRIVILEGE_ID, NAME) VALUES ('3', 'PERM_EDIT_USER');
INSERT INTO PRIVILEGE (PRIVILEGE_ID, NAME) VALUES ('4', 'PERM_CHANGE_ACTIVE_USER');
INSERT INTO PRIVILEGE (PRIVILEGE_ID, NAME) VALUES ('5', 'PERM_VIEW_USERFLAG');

INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('1', '0');
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('1', '1');
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('1', '2');
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('1', '3');
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('1', '4');
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('1', '5');
INSERT INTO ROLE_PRIVILEGE (ROLE_ID, PRIVILEGE_ID) VALUES ('2', '1');



INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES ('1', '1');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES ('2', '2');